# Generated by Django 4.2.5 on 2024-06-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0005_customuser_bio_customuser_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
