# Generated by Django 5.0.6 on 2024-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0007_spaces_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/messages/'),
        ),
    ]
