# Generated by Django 5.0.6 on 2024-06-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/'),
        ),
    ]
